### ISSUE TITLE
UWP App readiness

### ISSUE THREAD

**Issue by TheEngineerGuy** [DevPlus31/Moonlight-common#1]
Hi Bud,
First of all, let me thank you for the UWP effort, atleast someone is working on it.

In regards to the code itself, is ready to be compiled and distributed, or still awaiting something?

Please advise.

**Comment by DevPlus31** [comment]
Hello, 

This project is still under development, since I do not really have time to finish it, I have suspended it development for a certain period, then I'll resume it 

Thank you for your support.
And don't worry the project isn't dead.
